version: '3'

services:
  library-service:
    image: 'efirenet/library-service'
    ports:
      - "8081:8081"
    build:
      context: .
      #context: library-service
      dockerfile: Dockerfile
    networks:
      - library-sample-net
    depends_on:
      - db
      - keycloak
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://db:5432/lib_postgres",
        "spring.datasource.username" : "libpostgres",
        "spring.datasource.password" : "libpostgres",
        "spring.datasource.hikari.schema": "libdb",
        "spring.jpa.hibernate.ddl-auto" : "create-drop",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "springdoc.swagger-ui.path" : "/swagger-ui-custom.html",
        "logging.level.org.hibernate.SQL" : "DEBUG",
        "logging.level.org.hibernate.type.descriptor.sql.BasicBinder" : "TRACE"
      }'

  # Reference: https://graspingtech.com/docker-compose-postgresql/
  db:
    image: 'postgres:13.1-alpine'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=libpostgres
      - APP_DB_PASS=libpostgres
      - APP_DB_NAME=lib_postgres
      - APP_DB_SCHEMA=libdb
    networks:
      - library-sample-net
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  keycloakdb:
    image: 'postgres:13.1-alpine'
    container_name: keycloakdb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=keycloak
      - APP_DB_PASS=password
      - APP_DB_NAME=keycloak
      - APP_DB_SCHEMA=public
    networks:
      - library-sample-net
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloakdb
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        DB_SCHEMA: public
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      # Not able to pre-configure via import (need to manually import the json file)
      #  KEYCLOAK_IMPORT: ./keycloak/library-realm-export.json
      # volumes:
      #  - ./keycloak/library-realm-export.json:/tmp/realm-export.json
      ports:
        - "8080:8080"
      networks:
        - library-sample-net
      depends_on:
        - keycloakdb

volumes:
  postgres_data:
    driver: local

networks:
  library-sample-net:
    driver: bridge